-- Phase 5: richer audit fields
ALTER TABLE "AuditEvent" ADD COLUMN IF NOT EXISTS "ip" TEXT NOT NULL DEFAULT '';
ALTER TABLE "AuditEvent" ADD COLUMN IF NOT EXISTS "userAgent" TEXT NOT NULL DEFAULT '';
ALTER TABLE "AuditEvent" ADD COLUMN IF NOT EXISTS "before" JSONB;
ALTER TABLE "AuditEvent" ADD COLUMN IF NOT EXISTS "after" JSONB;
