import type { CSSProperties } from 'react';
import {
  LayoutDashboard,
  Send,
  Map,
  FileText,
  Users,
  Truck,
  TableProperties,
  BarChart3,
  Calculator,
  Building2,
  FolderOpen,
  FileSignature,
  CircleDot,
  Route,
  Timer,
  CheckCircle2,
  Clock,
  ArrowUpRight,
  ArrowDownRight,
  Search,
  Bell,
  User,
  Settings,
  Link,
  Sun,
  Moon,
  LogOut,
  Edit2,
  Trash2,
  Eye,
  Printer,
  Upload,
  Copy,
  Phone,
  MapPin,
  Package,
  Save,
  Square,
  XCircle,
  CheckCircle,
  Navigation,
  Plus,
  ChevronLeft,
  ChevronRight,
  AlertCircle
} from 'lucide-react';

type IconProps = { size?: number; color?: string; style?: CSSProperties };

export const Icons = {
  dashboard: (p?: IconProps) => <LayoutDashboard {...p} strokeWidth={1.75} />,
  dispatch: (p?: IconProps) => <Send {...p} strokeWidth={1.75} />,
  track: (p?: IconProps) => <Map {...p} strokeWidth={1.75} />,
  emanifest: (p?: IconProps) => <FileText {...p} strokeWidth={1.75} />,
  drivers: (p?: IconProps) => <Users {...p} strokeWidth={1.75} />,
  assets: (p?: IconProps) => <Truck {...p} strokeWidth={1.75} />,
  sheets: (p?: IconProps) => <TableProperties {...p} strokeWidth={1.75} />,
  reports: (p?: IconProps) => <BarChart3 {...p} strokeWidth={1.75} />,
  accounting: (p?: IconProps) => <Calculator {...p} strokeWidth={1.75} />,
  companies: (p?: IconProps) => <Building2 {...p} strokeWidth={1.75} />,
  docs: (p?: IconProps) => <FolderOpen {...p} strokeWidth={1.75} />,
  contract: (p?: IconProps) => <FileSignature {...p} strokeWidth={1.75} />,
  status: (p?: IconProps) => <CircleDot {...p} strokeWidth={1.75} />,
  trips: (p?: IconProps) => <Route {...p} strokeWidth={1.75} />,
  running: (p?: IconProps) => <Timer {...p} strokeWidth={1.75} />,
  completed: (p?: IconProps) => <CheckCircle2 {...p} strokeWidth={1.75} />,
  pending: (p?: IconProps) => <Clock {...p} strokeWidth={1.75} />,
  revenue: (p?: IconProps) => <ArrowUpRight {...p} strokeWidth={1.75} />,
  expenses: (p?: IconProps) => <ArrowDownRight {...p} strokeWidth={1.75} />,
  search: (p?: IconProps) => <Search {...p} strokeWidth={1.75} />,
  bell: (p?: IconProps) => <Bell {...p} strokeWidth={1.75} />,
  user: (p?: IconProps) => <User {...p} strokeWidth={1.75} />,
  driver: (p?: IconProps) => <User {...p} strokeWidth={1.75} />,
  vehicle: (p?: IconProps) => <Truck {...p} strokeWidth={1.75} />,
  chart: (p?: IconProps) => <BarChart3 {...p} strokeWidth={1.75} />,
  plus: (p?: IconProps) => <Plus {...p} strokeWidth={1.75} />,
  chevronLeft: (p?: IconProps) => <ChevronLeft {...p} strokeWidth={1.75} />,
  chevronRight: (p?: IconProps) => <ChevronRight {...p} strokeWidth={1.75} />,
  trendUp: (p?: IconProps) => <ArrowUpRight {...p} strokeWidth={1.75} />,
  trendDown: (p?: IconProps) => <ArrowDownRight {...p} strokeWidth={1.75} />,
  cancelled: (p?: IconProps) => <XCircle {...p} strokeWidth={1.75} />,
  assigned: (p?: IconProps) => <CheckCircle {...p} strokeWidth={1.75} />,
  truck: (p?: IconProps) => <Truck {...p} strokeWidth={1.75} />,
  trailer: (p?: IconProps) => <Package {...p} strokeWidth={1.75} />,
  alert: (p?: IconProps) => <AlertCircle {...p} strokeWidth={1.75} />,
  settings: (p?: IconProps) => <Settings {...p} strokeWidth={1.75} />,
  link: (p?: IconProps) => <Link {...p} strokeWidth={1.75} />,
  sun: (p?: IconProps) => <Sun {...p} strokeWidth={1.75} />,
  moon: (p?: IconProps) => <Moon {...p} strokeWidth={1.75} />,
  logout: (p?: IconProps) => <LogOut {...p} strokeWidth={1.75} />,
  edit: (p?: IconProps) => <Edit2 {...p} strokeWidth={1.75} />,
  trash: (p?: IconProps) => <Trash2 {...p} strokeWidth={1.75} />,
  eye: (p?: IconProps) => <Eye {...p} strokeWidth={1.75} />,
  print: (p?: IconProps) => <Printer {...p} strokeWidth={1.75} />,
  upload: (p?: IconProps) => <Upload {...p} strokeWidth={1.75} />,
  copy: (p?: IconProps) => <Copy {...p} strokeWidth={1.75} />,
  phone: (p?: IconProps) => <Phone {...p} strokeWidth={1.75} />,
  pin: (p?: IconProps) => <MapPin {...p} strokeWidth={1.75} />,
  box: (p?: IconProps) => <Package {...p} strokeWidth={1.75} />,
  save: (p?: IconProps) => <Save {...p} strokeWidth={1.75} />,
  border: (p?: IconProps) => <Square {...p} strokeWidth={1.75} />,
  canada: (p?: IconProps) => <Navigation {...p} strokeWidth={1.75} />,
  usa: (p?: IconProps) => <Navigation {...p} strokeWidth={1.75} />,
};

export type NavIconId = keyof typeof Icons;

export function NavIcon({
  id,
  size = 20,
  color,
}: {
  id: string;
  size?: number;
  color?: string;
}) {
  const key = id as NavIconId;
  const Comp = Icons[key] || Icons.dashboard;
  return Comp({ size, color });
}
