/** Common CA/US freight hubs for searchable origin/destination. */
export const FREIGHT_LOCATIONS = [
  // Canada
  'Calgary, AB',
  'Edmonton, AB',
  'Red Deer, AB',
  'Lethbridge, AB',
  'Medicine Hat, AB',
  'Grande Prairie, AB',
  'Vancouver, BC',
  'Surrey, BC',
  'Burnaby, BC',
  'Abbotsford, BC',
  'Kelowna, BC',
  'Prince George, BC',
  'Kamloops, BC',
  'Victoria, BC',
  'Winnipeg, MB',
  'Brandon, MB',
  'Toronto, ON',
  'Mississauga, ON',
  'Brampton, ON',
  'Hamilton, ON',
  'London, ON',
  'Ottawa, ON',
  'Windsor, ON',
  'Kitchener, ON',
  'Vaughan, ON',
  'Markham, ON',
  'Montreal, QC',
  'Laval, QC',
  'Quebec City, QC',
  'Saskatoon, SK',
  'Regina, SK',
  'Halifax, NS',
  'Moncton, NB',
  'Saint John, NB',
  'St. John\'s, NL',
  // USA (cross-border)
  'Seattle, WA',
  'Tacoma, WA',
  'Spokane, WA',
  'Portland, OR',
  'Los Angeles, CA',
  'Ontario, CA',
  'San Francisco, CA',
  'Phoenix, AZ',
  'Denver, CO',
  'Salt Lake City, UT',
  'Dallas, TX',
  'Houston, TX',
  'Chicago, IL',
  'Detroit, MI',
  'Buffalo, NY',
  'New York, NY',
  'Atlanta, GA',
  'Miami, FL',
  'Minneapolis, MN',
  'Kansas City, MO',
  'Fargo, ND',
  'Billings, MT',
  'Boise, ID',
] as const;

export type FreightLocation = (typeof FREIGHT_LOCATIONS)[number];
